# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-12 19:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoLargo',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('dni_nit', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000L), django.core.validators.MinValueValidator(0)])),
                ('fecha_inicial', models.DateTimeField(max_length=16)),
                ('fecha_final', models.DateTimeField(max_length=16)),
                ('fecha_deposito', models.DateTimeField(max_length=16)),
                ('monto_total', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('monto_depositado', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])), django.core.validators.MinValueValidator(1)])),
                ('monto_faltante', models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_completo_actividad', models.CharField(blank=True, max_length=255)),
                ('numero_factura', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000L), django.core.validators.MinValueValidator(0)])),
                ('numero_deposito', models.BigIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000000000L), django.core.validators.MinValueValidator(0)])),
                ('lugar', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('mult_dia', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('ver_formLic', 'ver formulario licenciada'), ('ver_formUsr', 'Ver formulario usuario'), ('editarUsr', 'Ver editar usuario'), ('Registrar', 'insertar registros'), ('FiltroLIc', 'filtrado fechas lugar')),
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='promediomulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=7)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos_largos.Lugar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='espacio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos_largos.Lugar'),
        ),
        migrations.AddField(
            model_name='contratolargo',
            name='espacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos_largos.Espacio'),
        ),
        migrations.AddField(
            model_name='contratolargo',
            name='porcentaje_multa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos_largos.promediomulta'),
        ),
        migrations.AddField(
            model_name='contratolargo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
