# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-25 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_largos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratolargo',
            options={'ordering': ['id'], 'permissions': (('ver_formLic', 'ver formulario licenciada'), ('ver_formUsr', 'Ver formulario usuario'), ('editarUsr', 'Ver editar usuario'), ('Registrar', 'insertar registros'), ('FiltroLIc', 'filtrado fechas lugar'), ('permiso_url_listlicenciada', 'permisos de url en listar licenciada'), ('permiso_url_listusuario', 'permisos de url en listar usuario'), ('permiso_url_crear_registros', 'permisos de url en crear usuario'))},
        ),
    ]
