# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_largos', '0002_auto_20190625_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratolargo',
            name='numero_deposito',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratolargo',
            name='numero_factura',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
