# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-27 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_largos', '0004_auto_20190823_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_lugar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
